version: "3.8"

name: booking_app_debug

services:
  authentification_service:
    image: authentification_service
    container_name: authentification_service
    build:
      context: .
      dockerfile: ./AuthentificationService/Dockerfile.debug
    restart: on-failure
    ports:
      - 11001:11001
    environment:
      AUTHENTIFICATION_SERVICE_PORT: ${AUTHENTIFICATION_SERVICE_PORT}
      AUTHENTIFICATION_DB_HOST: ${AUTHENTIFICATION_DB_HOST}
      AUTHENTIFICATION_DB_PORT: ${AUTHENTIFICATION_DB_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      DELETE_USER_COMMAND_SUBJECT: ${DELETE_USER_COMMAND_SUBJECT}
      DELETE_USER_REPLY_SUBJECT: ${DELETE_USER_REPLY_SUBJECT}
    depends_on:
      authentification_db:
        condition: service_healthy
    networks:
      - network

  user_service:
    image: user_service
    container_name: user_service
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
    restart: on-failure
    ports:
      - 11002:11002
    environment:
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      USER_DB_HOST: ${USER_DB_HOST}
      USER_DB_PORT: ${USER_DB_PORT}
      EMAIL_SERVICE_PORT: ${EMAIL_SERVICE_PORT}
      EMAIL_SERVICE_HOST: ${EMAIL_SERVICE_HOST}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      DELETE_USER_COMMAND_SUBJECT: ${DELETE_USER_COMMAND_SUBJECT}
      DELETE_USER_REPLY_SUBJECT: ${DELETE_USER_REPLY_SUBJECT}
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - network

  accommodation_service:
    image: accommodation_service
    container_name: accommodation_service
    build:
      context: .
      dockerfile: ./AccommodationService/Dockerfile
    restart: on-failure
    ports:
      - ${ACCOMMODATION_SERVICE_PORT}:${ACCOMMODATION_SERVICE_PORT}
      - 11003:11003
    environment:
      ACCOMMODATION_SERVICE_PORT: ${ACCOMMODATION_SERVICE_PORT}
      ACCOMMODATION_DB_HOST: ${ACCOMMODATION_DB_HOST}
      ACCOMMODATION_DB_PORT: ${ACCOMMODATION_DB_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      DELETE_USER_COMMAND_SUBJECT: ${DELETE_USER_COMMAND_SUBJECT}
      DELETE_USER_REPLY_SUBJECT: ${DELETE_USER_REPLY_SUBJECT}
    depends_on:
      accommodation_db:
        condition: service_healthy
    networks:
      - network

  reservation_service:
    image: reservation_service
    container_name: reservation_service
    build:
      context: .
      dockerfile: ./ReservationService/Dockerfile
    restart: on-failure
    ports:
      - ${RESERVATION_SERVICE_PORT}:${RESERVATION_SERVICE_PORT}
      - 11004:11004
    environment:
      RESERVATION_SERVICE_PORT: ${RESERVATION_SERVICE_PORT}
      RESERVATION_DB_HOST: ${RESERVATION_DB_HOST}
      RESERVATION_DB_PORT: ${RESERVATION_DB_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      DELETE_USER_COMMAND_SUBJECT: ${DELETE_USER_COMMAND_SUBJECT}
      DELETE_USER_REPLY_SUBJECT: ${DELETE_USER_REPLY_SUBJECT}
      NOTIFICATION_SUBJECT: ${NOTIFICATION_SUBJECT}
    depends_on:
      reservation_db:
        condition: service_healthy
    networks:
      - network
    
  email_service:
    image: email_service
    container_name: email_service
    build:
      context: .
      dockerfile: ./EmailService/Dockerfile
    restart: on-failure
    ports:
      - ${EMAIL_SERVICE_PORT}:${EMAIL_SERVICE_PORT}
      - 11005:11005
    environment:
      EMAIL_SERVICE_PORT: ${EMAIL_SERVICE_PORT}
      EMAIL_DB_HOST: ${EMAIL_DB_HOST}
      EMAIL_DB_PORT: ${EMAIL_DB_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      NOTIFICATION_SUBJECT: ${NOTIFICATION_SUBJECT}
    networks:
      - network

  recommendation_service:
    image: recommendation_service
    container_name: recommendation_service
    build:
      context: .
      dockerfile: ./RecommendationService/Dockerfile
    restart: on-failure
    ports:
      - ${RECOMMENDATION_SERVICE_PORT}:${RECOMMENDATION_SERVICE_PORT}
      - 11006:11006
    environment:
      RECOMMENDATION_SERVICE_PORT: ${RECOMMENDATION_SERVICE_PORT}
      RECOMMENDATION_DB_HOST: ${RECOMMENDATION_DB_HOST}
      RECOMMENDATION_DB_PORT: ${RECOMMENDATION_DB_PORT}
    depends_on:
        recommendation_db:
          condition: service_healthy
    networks:
      - network

  rating_service:
    image: rating_service
    container_name: rating_service
    build:
      context: .
      dockerfile: ./RatingService/Dockerfile
    restart: on-failure
    ports:
      - ${RATING_SERVICE_PORT}:${RATING_SERVICE_PORT}
      - 11007:11007
    environment:
      RATING_SERVICE_PORT: ${RATING_SERVICE_PORT}
      RATING_DB_HOST: ${RATING_DB_HOST}
      RATING_DB_PORT: ${RATING_DB_PORT}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      NOTIFICATION_SUBJECT: ${NOTIFICATION_SUBJECT}
      DELETE_USER_COMMAND_SUBJECT: ${DELETE_USER_COMMAND_SUBJECT}
      DELETE_USER_REPLY_SUBJECT: ${DELETE_USER_REPLY_SUBJECT}
    depends_on:
      rating_db:
        condition: service_healthy
    networks:
      - network

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./APIGateway/Dockerfile
    restart: on-failure
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
      - 11000:11000
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      AUTHENTIFICATION_SERVICE_HOST: ${AUTHENTIFICATION_SERVICE_HOST}
      AUTHENTIFICATION_SERVICE_PORT: ${AUTHENTIFICATION_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      ACCOMMODATION_SERVICE_HOST: ${ACCOMMODATION_SERVICE_HOST}
      ACCOMMODATION_SERVICE_PORT: ${ACCOMMODATION_SERVICE_PORT}
      RESERVATION_SERVICE_HOST: ${RESERVATION_SERVICE_HOST}
      RESERVATION_SERVICE_PORT: ${RESERVATION_SERVICE_PORT}
      API_GATEWAY_DB_HOST: ${API_GATEWAY_DB_HOST}
      API_GATEWAY_DB_PORT: ${API_GATEWAY_DB_PORT}
      RECOMMENDATION_SERVICE_PORT: ${RECOMMENDATION_SERVICE_PORT}
      RECOMMENDATION_SERVICE_HOST: ${RECOMMENDATION_SERVICE_HOST}
      RATING_SERVICE_PORT: ${RATING_SERVICE_PORT}
      RATING_SERVICE_HOST: ${RATING_SERVICE_HOST}
      EMAIL_SERVICE_PORT: ${EMAIL_SERVICE_PORT}
      EMAIL_SERVICE_HOST: ${EMAIL_SERVICE_HOST}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PASS: ${NATS_PASS}
      NOTIFICATION_SUBJECT: ${NOTIFICATION_SUBJECT}
    depends_on:
        api_gateway_db:
          condition: service_healthy
        authentification_service:
          condition: service_started
    networks:
      - network

  authentification_db:
    image: mongo
    container_name: authentification_db
    restart: on-failure
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "${AUTHENTIFICATION_DB_EXTERNAL_PORT}:27017"
    volumes:
      - authentification_db:/data/db
    networks:
      - network

  user_db:
    image: mongo
    container_name: user_db
    restart: on-failure
    ports:
      - "${USER_DB_EXTERNAL_PORT}:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - user_db:/data/db
    networks:
      - network

  accommodation_db:
    image: mongo
    container_name: accommodation_db
    restart: on-failure
    ports:
      - "${ACCOMMODATION_DB_EXTERNAL_PORT}:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - accommodation_db:/data/db
    networks:
      - network

  reservation_db:
    image: mongo
    container_name: reservation_db
    restart: on-failure
    ports:
      - "${RESERVATION_DB_EXTERNAL_PORT}:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - reservation_db:/data/db
    networks:
      - network
  
  rating_db:
    image: mongo
    container_name: rating_db
    restart: on-failure
    ports:
      - "${RATING_DB_EXTERNAL_PORT}:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - rating_db:/data/db
    networks:
      - network
    
  recommendation_db:
    image: neo4j:latest
    container_name: recommendation_db
    restart: on-failure
    ports:
      - "${RECOMMENDATION_DB_EXTERNAL_PORT}:7474"
      - "${RECOMMENDATION_DB_EXTERNAL_PORT2}:7687"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - recommendation_db_data:/data
      - recommendation_db_conf:/conf/
    networks:
      - network

  email_db:
    image: mongo
    container_name: email_db
    restart: on-failure
    ports:
      - "${EMAIL_DB_EXTERNAL_PORT}:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - email_db:/data/db
    networks:
      - network
      
  api_gateway_db:
    image: mongo
    container_name: api_gateway_db
    restart: on-failure
    ports:
      - "${API_GATEWAY_DB_EXTERNAL_PORT}:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - api_gateway_db:/data/db
    networks:
      - network
  
  nats:
    image: nats
    container_name: nats
    restart: on-failure
    ports:
      - "${NATS_EXTERNAL_PORT}:4222"
    networks:
      - network

networks:
  network:
    driver: bridge
  
volumes:
  authentification_db:
  user_db:
  accommodation_db:
  reservation_db:
  api_gateway_db:
  rating_db:
  email_db:
  recommendation_db_data:
  recommendation_db_conf: