FROM golang:latest as builder

EXPOSE 9000 10000

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

RUN CGO_ENABLED=0 GOOS=linux go build -gcflags "all=-N -l" -a -installsuffix cgo -o main .

CMD ["/go/bin/dlv", "--listen=:10000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/app/main"]